added support for ubuntu 24.04 and 22.04 with updated docker v27.2
IndustryFusion/DigitalTwin pull request #591
Opened 2024-09-20 11:21 UTC by yshashix

updated prepare-platform script with new docker version and updated way of adding keys to download as old apt-key way will be deprecated

2024-10-28 09:57 UTC, wagmarcel reviewed
Why is the K8s test missing now? I see only 3 e2e tests executed.
Also, I see that the test is not started at all: [Error](https://github.com/IndustryFusion/DigitalTwin/actions/runs/11544394192/workflow)
a step cannot have both the `uses` and `run` keys

2024-10-28 14:17 UTC, yshashix commented
> Why is the K8s test missing now? I see only 3 e2e tests executed. Also, I see that the test is not started at all: [Error](https://github.com/IndustryFusion/DigitalTwin/actions/runs/11544394192/workflow) a step cannot have both the `uses` and `run` keys

I have fixed the issue of [Error] where steps cant have both. and modified script.

2024-10-29 20:37 UTC, wagmarcel requested changes

2024-10-29 20:37 UTC, wagmarcel commented on semantic-model/shacl2flink/pyenv_setup.sh
I see a lot of tildes. Is there a reason why we install it in user's home instead of in DigitalTwin root directory?

2024-11-01 14:48 UTC, yshashix commented on semantic-model/shacl2flink/pyenv_setup.sh
When users install Miniconda, I thought to add it in the home directory so that they can use it not only specifically for Digital Twin but also to create Python environment across any other environment and vice versa. But when I re-think, it would be better to add it inside DigitalTwin repo as it is a requirement of DT.

2024-11-03 12:02 UTC, wagmarcel commented on semantic-model/shacl2flink/pyenv_setup.sh
So you will remove the pyenv_setup.sh or change it?

2024-11-03 13:27 UTC, yshashix commented on semantic-model/shacl2flink/pyenv_setup.sh
I have updated PR with the location of installation on the shacl2flink folder where pyenv_setup.sh runs.

2025-01-31 14:23 UTC, wagmarcel approved these changes

2025-01-31 14:23 UTC, merged